defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    timeout_min: 1440 # 24 hrs
    gpus_per_task: 1
    gres: gpu:1
    partition: rtx3080
    setup:
     - source envs/torch/bin/activate

    additional_parameters:
      mail_type: END,FAIL
