_target_: utils.audio_proc.ButterflyMFCC

n_mfcc: 32
melkwargs:
        n_fft: 2048
        hop_length: 512
        mel_scale: slaney
        norm: slaney
        pad_mode: constant
        f_max: 8000
